name: mlflow-ci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - scikit-learn=1.0.2
  - pandas=1.3.5
  - xgboost=1.5.0
  - mlflow=1.23.0
  - numpy=1.20.3 
  - pip:
      - protobuf==3.20.3
