name: mlflow-ci-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9 # Pastikan versi Python sesuai dengan kebutuhan Anda
  - pip
  - scikit-learn=1.0.2 # Versi yang kompatibel
  - pandas=1.3.5
  - xgboost=1.5.0 # Menambahkan XGBoost
  - mlflow=1.23.0 # Pastikan versi MLflow yang digunakan
  - pip:
      # Dependensi tambahan jika ada
