name: MLflow CI/CD Workflow (Skilled Level)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    environment: Production
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

    steps:
      - name: Set up job
        run: echo "Setting up the job..."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check Env
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          python --version
          conda --version
          pip --version
        shell: bash -l {0}

      - name: Install dependencies
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda env remove --name mlflow-ci-env || true
          conda env create -f MLProjects/conda.yaml
          conda activate mlflow-ci-env
        shell: bash -l {0}

      - name: Set MLflow Tracking URI
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate mlflow-ci-env
          mlflow server --host 127.0.0.1 --port 5001 --backend-store-uri sqlite:///mlruns.db --default-artifact-root ./mlruns &
          
          echo "Menunggu MLflow Server dimulai..."
          timeout_seconds=60
          start_time=$(date +%s)
          while ! curl -s http://127.0.0.1:5001 > /dev/null; do
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            if [ "$elapsed" -ge "$timeout_seconds" ]; then
              echo "MLflow Server tidak dimulai dalam $timeout_seconds detik."
              exit 1
            fi
            echo "MLflow Server belum siap. Menunggu 5 detik..."
            sleep 5
          done
          echo "MLflow Server berjalan dan siap!"
        shell: bash -l {0}

      - name: Run mlflow project
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate mlflow-ci-env
          export MLFLOW_TRACKING_URI="http://127.0.0.1:5001"
          export MLFLOW_REGISTRY_URI="http://127.0.0.1:5001"
          mlflow run MLProjects -e main --experiment-name "Shipping Delay Prediction"
        shell: bash -l {0}

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate mlflow-ci-env
          export MLFLOW_TRACKING_URI="http://127.0.0.1:5001"
          export MLFLOW_REGISTRY_URI="http://127.0.0.1:5001"

          sudo apt-get update && sudo apt-get install -y jq || true
          
          LATEST_RUN_ID=""
          echo "Mencoba mengambil MLflow run_id terbaru dengan percobaan ulang..."
          timeout_seconds=90
          start_time=$(date +%s)
          
          while [ -z "$LATEST_RUN_ID" ]; do
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            if [ "$elapsed" -ge "$timeout_seconds" ]; then
              echo "Gagal mengambil MLflow run_id dalam $timeout_seconds detik."
              exit 1
            fi
            
            MLFLOW_SEARCH_OUTPUT=$(mlflow search runs --experiment-name "Shipping Delay Prediction" --max-results 1 --order-by "start_time DESC" --output-format json)
            
            echo "Output mentah mlflow search runs (percobaan ke-${elapsed}s):"
            echo "$MLFLOW_SEARCH_OUTPUT"
            
            if [ "$(echo "$MLFLOW_SEARCH_OUTPUT" | jq 'length')" -gt 0 ]; then
              RUN_ID_CANDIDATE=$(echo "$MLFLOW_SEARCH_OUTPUT" | jq -r '.[0].info.run_id // empty')
              if [ -n "$RUN_ID_CANDIDATE" ]; then
                LATEST_RUN_ID="$RUN_ID_CANDIDATE"
                echo "Berhasil mengambil LATEST_RUN_ID: $LATEST_RUN_ID"
                break
              fi
            fi
            
            echo "MLflow run_id belum ditemukan. Menunggu 5 detik sebelum mencoba lagi..."
            sleep 5
          done

          if [ -z "$LATEST_RUN_ID" ]; then
            echo "Error: LATEST_RUN_ID kosong setelah semua percobaan ulang. Tidak dapat melanjutkan."
            exit 1
          fi

          echo "latest_run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT
        shell: bash -l {0}

      - name: Install Python dependencies
        run: |
          source "$(conda info --base)/etc/profile.d/conda.sh"
          conda activate mlflow-ci-env
        shell: bash -l {0}

      - name: Upload to Google Drive
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts-${{ github.run_id }}
          path: mlruns/${{ steps.get_run_id.outputs.latest_run_id }}/artifacts/

      - name: Complete job
        run: echo "Job completed successfully!"
