name: MLflow CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Check Env
        run: |
          python --version
          pip --version

      - name: Install dependencies
        run: |
          pip install mlflow==1.23.0
          pip install conda
          conda env create -f MLProject/conda.yaml

      - name: Start MLflow Tracking Server (Local) # LANGKAH BARU INI!
        run: |
          # Aktifkan environment Conda
          source ~/.bashrc
          conda activate mlflow-ci-env
          # Mulai MLflow UI di background, menggunakan direktori mlruns lokal
          # Perhatikan '&' di akhir untuk menjalankan di background
          mlflow ui --host 127.0.0.1 --port 5001 --backend-store-uri ./mlruns &
          # Beri waktu sebentar agar server sempat menyala
          sleep 5
          # Atur MLFLOW_TRACKING_URI sebagai environment variable untuk langkah selanjutnya
          export MLFLOW_TRACKING_URI="http://127.0.0.1:5001"

      - name: Run MLflow Project
        run: |
          # Perintah ini akan menggunakan MLFLOW_TRACKING_URI yang sudah diexport di langkah sebelumnya
          source ~/.bashrc
          conda activate mlflow-ci-env
          mlflow run MLProject -e main

      - name: Get latest MLflow run_id
        id: get_run_id
        run: |
          LATEST_RUN_ID=$(ls -td mlruns/*/ | head -1 | xargs basename)
          echo "latest_run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT

      - name: Save MLflow Run Data as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: mlflow-run-artifacts-${{ github.run_id }}
          path: mlruns/${{ steps.get_run_id.outputs.latest_run_id }}/artifacts/

      - name: Build Docker Model
        run: |
          source ~/.bashrc
          conda activate mlflow-ci-env
          mlflow models build-docker --model-uri "models:/ShippingDelayXGBoostModel/Production" -n shipping-delay-xgb-model:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          DOCKER_IMAGE_NAME="shipping-delay-xgb-model"
          DOCKER_REPO="${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME"
          docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_REPO:latest
          docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_REPO:${{ github.run_id }}

      - name: Push Docker Image
        run: |
          DOCKER_IMAGE_NAME="shipping-delay-xgb-model"
          DOCKER_REPO="${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE_NAME"
          docker push $DOCKER_REPO:latest
          docker push $DOCKER_REPO:${{ github.run_id }}
