name: MLflow CI/CD Workflow (Skilled Level)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-train:
    runs-on: ubuntu-latest
    environment: Production
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python

    steps:
      - name: Set up job
        run: echo "Setting up the job..."

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: |
          python --version
          conda --version
          pip --version
        shell: bash -l {0}

      - name: Install dependencies
        run: |
          conda env remove --name mlflow-ci-env || true
          conda env create -f MLProjects/conda.yaml
          conda activate mlflow-ci-env
        shell: bash -l {0}

      - name: Set MLflow Tracking URI
        run: |
          conda activate mlflow-ci-env
          python -m mlflow server --host 127.0.0.1 --port 5001 --backend-store-uri sqlite:///mlruns.db --default-artifact-root ./mlruns &
          
          echo "Menunggu MLflow Server dimulai..."
          timeout_seconds=60
          start_time=$(date +%s)
          while ! curl -s http://127.0.0.1:5001 > /dev/null; do
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            if [ "$elapsed" -ge "$timeout_seconds" ]; then
              echo "MLflow Server tidak dimulai dalam $timeout_seconds detik."
              exit 1
            fi
            echo "MLflow Server belum siap. Menunggu 5 detik..."
            sleep 5
          done
          echo "MLflow Server berjalan dan siap!"
        shell: bash -l {0}

      - name: Run mlflow project
        run: |
          conda activate mlflow-ci-env
          export MLFLOW_TRACKING_URI="http://127.0.0.1:5001"
          export MLFLOW_REGISTRY_URI="http://127.0.0.1:5001"
          python -m mlflow run MLProjects -e main --experiment-name "Shipping Delay Prediction"
        shell: bash -l {0}

      - name: Install Python dependencies
        run: |
          conda activate mlflow-ci-env
        shell: bash -l {0}

      - name: Upload to Google Drive
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-run-artifacts-${{ github.run_id }}
          path: mlruns/${{ steps.get_run_id.outputs.latest_run_id }}/artifacts/

      - name: Complete job
        run: echo "Job completed successfully!"
